### ISSUE TITLE
evil-swap-keys

### ISSUE THREAD

**Issue by wbolster** [Liu233w/number-lock.el#1]
hey, just to let you know, i recently published a similar package, specifically for evil-mode, that allows all kinds of key swaps, including numbers/symbols:

https://github.com/wbolster/evil-swap-keys

**Comment by wbolster** [comment]
i would be interested to hear why you decided to move away from `key-translation-map` to input methods, btw.

**Comment by Liu233w** [comment]
This is the version which use `key-translation-map` : https://github.com/Liu233w/programming-mode.el/blob/key-translate-mode/programming-mode.el

It works pretty well, but the number keys' behavior is different from the original at evil's normal state.

For example:

original: when I enter `1 2 3 4 5` at normal state
<img width="245" alt="8 27" src="https://cloud.githubusercontent.com/assets/16333687/18024425/55995b3e-6c3c-11e6-8e36-12c2caeda602.PNG">
after using that package and enter `1 2 3 4 5` at normal state:
<img width="171" alt="8 27 2" src="https://cloud.githubusercontent.com/assets/16333687/18024447/41252dc6-6c3d-11e6-9baf-a5bae055620b.PNG">

I don't know why. After that I saw [yangchenyun/programmer-dvorak](https://github.com/yangchenyun/programmer-dvorak) and it inspired me to use input method to translate keys.
